#!/bin/bash

export __dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

pushd $(dirname $(dirname ${__dir}))
    bundle install
    bundle exec rake db:reset
popd

pushd ${__dir}
    bundle exec rake db:seed
popd
